# Generated by Django 5.2.8 on 2026-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('ai', 'AI/ML'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
