# Generated by Django 5.2.8 on 2026-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('report', 'Report'), ('brief', 'Brief'), ('blog', 'Blog')], max_length=20)),
                ('file', models.FileField(upload_to='publications/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
