# Generated by Django 6.0.5 on 2026-05-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number can only contain digits, spaces, and + - ( ) symbols.",
                                regex="^[0-9+\\-\\s()]+$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("map_embed_url", models.URLField(blank=True)),
                ("office_hours", models.CharField(blank=True, max_length=255)),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact information",
                "verbose_name_plural": "Contact information",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number can only contain digits, spaces, and + - ( ) symbols.",
                                regex="^[0-9+\\-\\s()]+$",
                            )
                        ],
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("partnership", "Partnership"),
                            ("media", "Media"),
                            ("support", "Support"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("source_page", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
