# Generated by Django 6.0.5 on 2026-05-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="contactsubmission",
            options={},
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="map_embed_url",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="office_hours",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="twitter_url",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="youtube_url",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="inquiry_type",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
