# Generated by Django 6.0.5 on 2026-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
