# Generated by Django 5.2.8 on 2026-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('network', 'Network'), ('attack', 'Attack'), ('system', 'System'), ('ui', 'UI'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
